[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "/.next"

[build.environment]
  NEXT_PUBLIC_REFRESH_INTERVAL = "5000"
  TRELLO_KEY = ""
  TRELLO_TOKEN = ""
  IS_PUBLIC_BOARD = "false"
  