[build]
  base = "/"
  command = "npm ci && npm run build"
  functions = ".netlify/functions"

[template.environment]
  NEXT_PUBLIC_TRELLO_BOARD_ID="Trello Board ID"
  NEXT_PUBLIC_REFRESH_INTERVAL="Refresh Interval (in milliseconds)"
  NEXT_PUBLIC_WAIT_TIME_MINS="Waiting Time (in minutes)"
  APP_NAME="1. Application Name e.g. My QueueUp"
  TRELLO_KEY="2. Trello API Key"
  TRELLO_TOKEN="3. Trello API Token"
  IS_PUBLIC_BOARD="Public Board e.g. false"
  REDIRECT_URL="Admin Redirect Callback Url e.g. https://example.com/admin/callback"
  SCOPES="Trello Scopes e.g. read,write"
  EXPIRATION_DURATION="Authorisation Token Duration e.g. 1hours"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"