[build]
  base = "/"
  command = "npm ci && npm run build"
  functions = ".netlify/functions"

[template.environment]
  NEXT_PUBLIC_TRELLO_BOARD_ID="Trello Board ID"
  NEXT_PUBLIC_REFRESH_INTERVAL="Refresh Interval (in milliseconds)"
  NEXT_PUBLIC_WAIT_TIME_MINS="Waiting Time (in minutes)"
  TRELLO_KEY="Trello API Key"
  TRELLO_TOKEN="Trello API Token"
  IS_PUBLIC_BOARD="Public Board (True/False)"
  REDIRECT_URL="https://example.com/admin/callback"
  SCOPES="read,write"
  EXPIRATION_DURATION="1hours"
  APP_NAME="My QueueUp"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"