[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "/.next"

[template.environment]
  NEXT_PUBLIC_TRELLO_BOARD_ID = ""
  NEXT_PUBLIC_REFRESH_INTERVAL = "5000"
  NEXT_PUBLIC_WAIT_TIME_MINS = "3"
  TRELLO_KEY = ""
  TRELLO_TOKEN = ""
  IS_PUBLIC_BOARD = "false"
  
