[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/frontend"
  environment = { IS_PUBLIC_BOARD = false, NEXT_PUBLIC_REFRESH_INTERVAL = "5000", TRELLO_KEY = "", TRELLO_TOKEN = "" }
